### ISSUE TITLE
Adverserial Training ???!

### ISSUE THREAD

**Issue by a-jahani** [andrea-pilzer/unsup-stereo-depthGAN#2]
Hi,

Thank you for the code! I learned a lot of things while reading your code.
I thoroughly read your code and paper but to my understanding, the way you trained doesn't seem like adversarial training.

In adversarial training, you have 2 optimizers. There is a loss in Generator part which is fighting with the loss in Discriminator and you train discriminator to fight back the generator. It's a min max optimization. 
In your case generator never fights back the discriminator / vise versa! and there is only one optimizer which is optimizing the generator!

Your approach of cycle is exactly like having monodepth left right consistency except you have more parameters now! I think a little improvement is not related to adversarial training!

Please fix me if I am wrong! 
Thank you

**Comment by andrea-pilzer** [comment]
Hi, thank you for pointing this to me. We were aware the github version is not correct and I will upload the correct code that I used.

**Comment by a-jahani** [comment]
Thank you for your quick reply. I'll be looking forward to it
