### ISSUE TITLE
Compared to 'mrharicot' method

### ISSUE THREAD

**Issue by DonghunP** [andrea-pilzer/unsup-stereo-depthGAN#6]
Dear author.

Thanks for sharing your code.

I just  wonder, does depth prediction using GAN can get higher accuracy than 

CNN method like 'mrharicot'? 

Thanks.

**Comment by andrea-pilzer** [comment]
Hi,
I did not try to apply adversarial learning to the code of Godard et al. "Unsupervised monocular depth estimation with left-right consistency" (if this is the paper you refer to). So let me know how it works if you plan to try it out.

Andrea
