### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by logsanand** [andrea-pilzer/unsup-stereo-depthGAN#8]
Hi, Thanks a lot for the code. I trained my model for around 24 hrs and it ended with a checkpoint of 141250. When I tested the model, I result was just a blue background. I used KITTI dataset and the same parameters as you have mentioned. I would like to know the checkpoint used by you.

**Comment by andrea-pilzer** [comment]
Hi, looks like you got a mode collapse from the adversarial learning. It did not happen to me so I will try to find the time to run again the training.

You can follow the link in the readme to have a pretrained model.

Note that you first have to pretrain the first half cycle --train_branch=b2a and then load the model and pretrain the second half cycle --train_branch=a2b and finally train all together --tran_branch=full, as described on the paper.

**Comment by logsanand** [comment]
Hi,
I initially trained the model b2a, then a2b and then full using
retrain[python main.py --dataset kitti --filenames_file
utils/filenames/eigen_train_files_png.txt --data_path ./data/KITTI/
--do_stereo --train_branch full --checkpoint_path
./stereo_depthGAN/model-141250 --retrain].
It took 24hrs for each training. Still, I could not get the depth. I am
just curious to know what I did wrong. Sorry to bother you.

Thank you,
Regards,
Logambal
